#!/bin/bash
# TurboGears OpenShift post-stop build configuration

set -e
export PATH=$PATH:~/$OPENSHIFT_APP_NAME/virtenv/bin/

source ~/$OPENSHIFT_APP_NAME/virtenv/bin/activate


# Have apache serve up all of our static resources
echo "Symlinking static resources from webbot/public"
ln -s $OPENSHIFT_REPO_DIR/wsgi/webbot/webbot/public/* $OPENSHIFT_REPO_DIR/wsgi/static/

cd $OPENSHIFT_REPO_DIR/wsgi/webbot

# We're not doing 'install' to save space.
python setup.py develop
